### ISSUE TITLE
Extra Parentheses In tweety.py

### ISSUE THREAD

**Issue by NBatarilo** [santhoshse7en/tweety#2]
There's an extra parentheses after ... item.text).split())on line 46 of tweety.py causing a compile error.

**Comment by santhoshse7en** [comment]
Solved

**Comment by NBatarilo** [comment]
I was wondering if there's any additional documentation for tweety? I've so far figured out how to access compiled tweets, but I was wondering if there's any way to limit the number of tweets you receive per query. I'd also love to contribute any helper functions like this if they don't already exist.
